version: '3.8'
services:
  postgres:
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - nestjs

volumes:
  postgres_volume:

networks:
  nestjs:
