// ユーザ登録
POST http://localhost:3000/auths/signup/
content-type: application/json
Accept: application/json

{
"name": "example1",
"email": "test1@example.com"
}
###

// 記事の登録
POST http://localhost:3000/articles/
content-type: application/json
Accept: application/json

{
    "content": "記事１",
    "userId": 1
}
###

// コメント登録
POST http://localhost:3000/articles/1/comments/
content-type: application/json
Accept: application/json

{
    "content": "コメント１",
    "userId": 1
}
###

// 記事のみ取得
GET http://localhost:3000/articles/1/
content-type: application/json
Accept: application/json

###